'use client';
import { useEffect, useState } from 'react';
import { Modal } from '../ui/Modal';
import { Button } from '../ui/Button';
import { FormField } from '../ui/FormField';
import { fieldClass } from '../../utils/styles';
import type { CustomerResponse } from '../../apis/customers';
import type { SalesmanResponse } from '../../apis/salesmen';
import type { TechnicianResponse } from '../../apis/technicians';
import type { MachineArea, MachineCompany, MachineCurrentStatus, MachineDivision, MachineModelResponse, MachineRequest, MachineResponse } from '../../apis/machines';

type Values = {
  customerId: string; siteName: string; addressLine1: string; addressLine2: string; addressLine3: string; area: MachineArea; cityId: string; latitude: string; longitude: string; isHeadOffice: boolean; siteActive: boolean;
  contactName: string; mobileNumber: string; email: string; designation: string; isPrimary: boolean; contactActive: boolean;
  invoiceNumber: string; belitaInvoiceNumber: string; invoiceDate: string; invoiceNote: string;
  serialNumber: string; company: MachineCompany; division: MachineDivision; modelId: string; currentStatus: MachineCurrentStatus; mainTechId: string; serviceTechId: string; dealerId: string; repId: string; salesmanId: string; installDate: string; machineNote: string; creditNoteNumber: string; statusReason: string;
};
const empty = (): Values => ({ customerId: '', siteName: '', addressLine1: '', addressLine2: '', addressLine3: '', area: 'COLOMBO', cityId: '', latitude: '', longitude: '', isHeadOffice: false, siteActive: true, contactName: '', mobileNumber: '', email: '', designation: '', isPrimary: true, contactActive: true, invoiceNumber: '', belitaInvoiceNumber: '', invoiceDate: '', invoiceNote: '', serialNumber: '', company: 'GESTETNER', division: 'OUTRIGHT', modelId: '', currentStatus: 'AVAILABLE', mainTechId: '', serviceTechId: '', dealerId: '', repId: '', salesmanId: '', installDate: '', machineNote: '', creditNoteNumber: '', statusReason: '' });
const fromMachine = (m: MachineResponse): Values => ({ customerId: String(m.customerId), siteName: m.siteName, addressLine1: m.addressLine1, addressLine2: m.addressLine2 ?? '', addressLine3: m.addressLine3 ?? '', area: m.area, cityId: String(m.cityId), latitude: m.latitude?.toString() ?? '', longitude: m.longitude?.toString() ?? '', isHeadOffice: m.isHeadOffice, siteActive: m.siteActive, contactName: m.contactName, mobileNumber: m.mobileNumber ?? '', email: m.email, designation: m.designation ?? '', isPrimary: m.isPrimaryContact, contactActive: m.contactActive, invoiceNumber: m.invoiceNumber, belitaInvoiceNumber: m.belitaInvoiceNumber ?? '', invoiceDate: m.invoiceDate ?? '', invoiceNote: m.invoiceNote ?? '', serialNumber: m.serialNumber, company: m.company, division: m.division, modelId: String(m.modelId), currentStatus: m.currentStatus, mainTechId: m.currentMainTechnicianId?.toString() ?? '', serviceTechId: m.currentServiceTechnicianId?.toString() ?? '', dealerId: m.dealerId?.toString() ?? '', repId: m.repId?.toString() ?? '', salesmanId: m.salesmanId?.toString() ?? '', installDate: m.originalInstallDate ?? '', machineNote: m.machineNote ?? '', creditNoteNumber: m.creditNoteNumber ?? '', statusReason: '' });

interface Props { open: boolean; machine: MachineResponse | null; customers: CustomerResponse[]; technicians: TechnicianResponse[]; salesmen: SalesmanResponse[]; models: MachineModelResponse[]; onCreateModel: () => void; onClose: () => void; onSave: (request: Omit<MachineRequest, 'performedBy'>) => Promise<void> }
export function MachineDialog({ open, machine, customers, technicians, salesmen, models, onCreateModel, onClose, onSave }: Props) {
  const [v, setV] = useState<Values>(empty); const [errors, setErrors] = useState<Record<string, string>>({}); const [saving, setSaving] = useState(false);
  useEffect(() => { if (open) setV(machine ? fromMachine(machine) : empty()); }, [open, machine]);
  const set = <K extends keyof Values>(key: K, value: Values[K]) => { setV((p) => ({ ...p, [key]: value })); setErrors((p) => ({ ...p, [key]: '' })); };
  const numberOrNull = (value: string) => value ? Number(value) : null;
  const submit = async () => { const next: Record<string, string> = {}; for (const [key, value] of Object.entries({ customerId: v.customerId, siteName: v.siteName, addressLine1: v.addressLine1, cityId: v.cityId, contactName: v.contactName, email: v.email, invoiceNumber: v.invoiceNumber, serialNumber: v.serialNumber, modelId: v.modelId })) if (!value.trim()) next[key] = 'Required'; if (v.email && !/^\S+@\S+\.\S+$/.test(v.email)) next.email = 'Enter a valid email'; setErrors(next); if (Object.keys(next).length) return;
    const request: Omit<MachineRequest, 'performedBy'> = { customerSite: { customerId: Number(v.customerId), siteName: v.siteName.trim(), addressLine1: v.addressLine1.trim(), addressLine2: v.addressLine2.trim() || null, addressLine3: v.addressLine3.trim() || null, area: v.area, cityId: Number(v.cityId), latitude: numberOrNull(v.latitude), longitude: numberOrNull(v.longitude), isHeadOffice: v.isHeadOffice, isActive: v.siteActive }, siteContact: { contactName: v.contactName.trim(), mobileNumber: v.mobileNumber.trim() || null, email: v.email.trim(), designation: v.designation.trim() || null, isPrimary: v.isPrimary, isActive: v.contactActive }, machineInvoice: { invoiceNumber: v.invoiceNumber.trim(), belitaInvoiceNumber: v.belitaInvoiceNumber.trim() || null, invoiceDate: v.invoiceDate || null, note: v.invoiceNote.trim() || null }, machine: { serialNumber: v.serialNumber.trim(), company: v.company, division: v.division, modelId: Number(v.modelId), currentStatus: v.currentStatus, currentMainTechnicianId: numberOrNull(v.mainTechId), currentServiceTechnicianId: numberOrNull(v.serviceTechId), dealerId: numberOrNull(v.dealerId), repId: numberOrNull(v.repId), salesmanId: numberOrNull(v.salesmanId), originalInstallDate: v.installDate || null, note: v.machineNote.trim() || null, creditNoteNumber: v.creditNoteNumber.trim() || null }, statusReason: v.statusReason.trim() || null };
    setSaving(true); try { await onSave(request); } catch {} finally { setSaving(false); }
  };
  const input = (key: keyof Values, label: string, type = 'text', required = false) => <FormField label={label} htmlFor={`m-${key}`} required={required} error={errors[key]}><input id={`m-${key}`} type={type} value={String(v[key])} onChange={(e) => set(key, e.target.value as never)} className={fieldClass(!!errors[key])} /></FormField>;
  const check = (key: 'isHeadOffice' | 'siteActive' | 'isPrimary' | 'contactActive', label: string) => <label className="flex items-center gap-2 text-sm text-ink"><input type="checkbox" checked={v[key]} onChange={(e) => set(key, e.target.checked)} />{label}</label>;
  const compatibleTechs = technicians.filter((t) => t.user.isActive && t.companies.includes(v.company)); const compatibleSalesmen = salesmen.filter((s) => s.user.isActive && s.companies.includes(v.company)); const compatibleModels = models.filter((m) => m.isActive && m.company === v.company);
  return <Modal open={open} onClose={() => !saving && onClose()} title={machine ? `Edit ${machine.machineReferenceNumber}` : 'Create machine'} description="Machine, customer site, contact and invoice details." widthClass="max-w-4xl" footer={<div className="flex justify-end gap-3"><Button variant="ghost" onClick={onClose} disabled={saving}>Cancel</Button><Button loading={saving} onClick={() => void submit()}>{machine ? 'Save changes' : 'Create machine'}</Button></div>}>
    <div className="space-y-7"><section><h3 className="mb-3 text-sm font-semibold">Machine</h3><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{input('serialNumber','Serial number','text',true)}
      <FormField label="Company" htmlFor="m-company" required><select id="m-company" value={v.company} onChange={(e) => { set('company', e.target.value as MachineCompany); set('modelId',''); set('mainTechId',''); set('serviceTechId',''); set('salesmanId',''); }} className={fieldClass()}><option>GESTETNER</option><option>FINTECH</option></select></FormField>
      <FormField label="Division" htmlFor="m-division" required><select id="m-division" value={v.division} onChange={(e) => set('division', e.target.value as MachineDivision)} className={fieldClass()}>{['RENTAL','OUTRIGHT','WORKSHOP','AC','PRODUCTION','ELECTRONIC'].map(x=><option key={x}>{x}</option>)}</select></FormField>
      <FormField label="Model" htmlFor="m-modelId" required error={errors.modelId} action={<button type="button" onClick={onCreateModel} className="text-xs font-medium text-brand-700 hover:text-brand-800">+ Create model</button>}><select id="m-modelId" value={v.modelId} onChange={(e)=>set('modelId',e.target.value)} className={fieldClass(!!errors.modelId)}><option value="">Select model</option>{compatibleModels.map(m=><option key={m.modelId} value={m.modelId}>{m.modelNumber} · {m.modelName}</option>)}</select></FormField>
      <FormField label="Status" htmlFor="m-status" required><select id="m-status" value={v.currentStatus} onChange={(e)=>set('currentStatus',e.target.value as MachineCurrentStatus)} className={fieldClass()}>{['AVAILABLE','INSTALLATION_PENDING','ACTIVE_FS','ACTIVE_MA','NO_SERVICE','OUT_OF_SERVICE','RETURNED','CREDIT_NOTE','REMOVED'].map(x=><option key={x}>{x}</option>)}</select></FormField>{input('installDate','Install date','date')}{input('creditNoteNumber','Credit note number')}{input('machineNote','Machine note')}{input('statusReason','Status reason')}</div></section>
    <section className="border-t border-line pt-6"><h3 className="mb-3 text-sm font-semibold">Customer site</h3><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><FormField label="Customer" htmlFor="m-customer" required error={errors.customerId}><select id="m-customer" value={v.customerId} onChange={(e)=>set('customerId',e.target.value)} className={fieldClass(!!errors.customerId)}><option value="">Select customer</option>{customers.filter(c=>c.isActive).map(c=><option key={c.customerId} value={c.customerId}>{c.customerName}</option>)}</select></FormField>{input('siteName','Site name','text',true)}{input('addressLine1','Address line 1','text',true)}{input('addressLine2','Address line 2')}{input('addressLine3','Address line 3')}<FormField label="Area" htmlFor="m-area" required><select id="m-area" value={v.area} onChange={(e)=>set('area',e.target.value as MachineArea)} className={fieldClass()}><option>COLOMBO</option><option>OUTSTATION</option><option>SUBURB</option></select></FormField>{input('cityId','City ID','number',true)}{input('latitude','Latitude','number')}{input('longitude','Longitude','number')}<div className="flex gap-4 sm:col-span-2">{check('isHeadOffice','Head office')}{check('siteActive','Active site')}</div></div></section>
    <section className="border-t border-line pt-6"><h3 className="mb-3 text-sm font-semibold">Contact & invoice</h3><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{input('contactName','Contact name','text',true)}{input('mobileNumber','Mobile','tel')}{input('email','Email','email',true)}{input('designation','Designation')}{input('invoiceNumber','Invoice number','text',true)}{input('belitaInvoiceNumber','Belita invoice')}{input('invoiceDate','Invoice date','date')}{input('invoiceNote','Invoice note')}<div className="flex gap-4">{check('isPrimary','Primary contact')}{check('contactActive','Active contact')}</div></div></section>
    <section className="border-t border-line pt-6"><h3 className="mb-3 text-sm font-semibold">Assignments</h3><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[['mainTechId','Main technician'],['serviceTechId','Service technician']].map(([key,label])=><FormField key={key} label={label} htmlFor={`m-${key}`}><select id={`m-${key}`} value={v[key as 'mainTechId']} onChange={(e)=>set(key as 'mainTechId',e.target.value)} className={fieldClass()}><option value="">None</option>{compatibleTechs.map(t=><option key={t.technicianId} value={t.technicianId}>{t.user.userName}</option>)}</select></FormField>)}<FormField label="Salesman" htmlFor="m-salesman"><select id="m-salesman" value={v.salesmanId} onChange={(e)=>set('salesmanId',e.target.value)} className={fieldClass()}><option value="">None</option>{compatibleSalesmen.map(s=><option key={s.salesmanId} value={s.salesmanId}>{s.user.userName}</option>)}</select></FormField>{input('dealerId','Dealer ID','number')}{input('repId','Rep ID','number')}</div></section></div>
  </Modal>;
}
