'use client';
import { useEffect, useState } from 'react'; import { CheckIcon } from 'lucide-react';
import { Modal } from '../ui/Modal'; import { Button } from '../ui/Button'; import { FormField } from '../ui/FormField'; import { fieldClass } from '../../utils/styles';
import type { AdminUserArea, AdminUserCompany, AdminUserDivision, CoordinatorResponse, CoordinatorRole, ManagedUserCreateRequest, ManagedUserKind, ManagedUserResponse, ManagedUserUpdateRequest } from '../../apis/adminUsers';

type Values={userName:string;mobileNumber:string;email:string;password:string;isActive:boolean;division:AdminUserDivision;area:AdminUserArea;companies:AdminUserCompany[];coordinatorRole:CoordinatorRole};
const empty=():Values=>({userName:'',mobileNumber:'',email:'',password:'',isActive:true,division:'RENTAL',area:'COLOMBO',companies:[],coordinatorRole:'AREA_MANAGER'});
export function ManagedUserDialog({kind,open,item,onClose,onSave}:{kind:ManagedUserKind;open:boolean;item:ManagedUserResponse|null;onClose:()=>void;onSave:(request:Omit<ManagedUserCreateRequest,'createdBy'>|Omit<ManagedUserUpdateRequest,'updatedBy'>)=>Promise<void>}){
 const[v,setV]=useState<Values>(empty);const[errors,setErrors]=useState<Record<string,string>>({});const[saving,setSaving]=useState(false);const editing=!!item;
 useEffect(()=>{if(open)setV(item?{userName:item.user.userName,mobileNumber:item.user.mobileNumber,email:item.user.email,password:'',isActive:item.user.isActive,division:item.user.division,area:item.user.area,companies:item.companies,coordinatorRole:kind==='coordinator'?(item as CoordinatorResponse).coordinatorRole:'AREA_MANAGER'}:empty());},[open,item,kind]);
 const set=<K extends keyof Values>(k:K,x:Values[K])=>{setV(p=>({...p,[k]:x}));setErrors(p=>({...p,[k]:''}));};
 const submit=async()=>{const e:Record<string,string>={};if(!v.userName.trim())e.userName='Name is required';if(!v.mobileNumber.trim())e.mobileNumber='Mobile is required';if(!/^\S+@\S+\.\S+$/.test(v.email))e.email='Enter a valid email';if(!editing&&v.password.length<8)e.password='Use at least 8 characters';if(editing&&v.password&&v.password.length<8)e.password='Use at least 8 characters';if(!editing&&!v.companies.length)e.companies='Select at least one company';setErrors(e);if(Object.keys(e).length)return;
  const base={userName:v.userName.trim(),mobileNumber:v.mobileNumber.trim(),email:v.email.trim(),...(v.password?{password:v.password}:{}),isActive:v.isActive,division:v.division,area:v.area,...(kind==='coordinator'?{coordinatorRole:v.coordinatorRole}:{})};const request=editing?base:{...base,password:v.password,companies:v.companies};setSaving(true);try{await onSave(request);}catch{}finally{setSaving(false);}};
 const input=(k:'userName'|'mobileNumber'|'email'|'password',label:string,type='text',required=false)=><FormField label={label} htmlFor={`u-${k}`} required={required} error={errors[k]} hint={editing&&k==='password'?'Leave blank to keep the current password':undefined}><input id={`u-${k}`} type={type} value={v[k]} onChange={x=>set(k,x.target.value)} className={fieldClass(!!errors[k])}/></FormField>;
 return <Modal open={open} onClose={()=>!saving&&onClose()} title={`${editing?'Edit':'Create'} ${kind==='coordinator'?'coordinator':'finance user'}`} widthClass="max-w-2xl" footer={<div className="flex justify-end gap-3"><Button variant="ghost" disabled={saving} onClick={onClose}>Cancel</Button><Button loading={saving} onClick={()=>void submit()}>{editing?'Save changes':'Create user'}</Button></div>}><div className="grid gap-4 sm:grid-cols-2">{input('userName','Full name','text',true)}{input('mobileNumber','Mobile number','tel',true)}{input('email','Email','email',true)}{input('password',editing?'New password':'Password','password',!editing)}
  <FormField label="Division" htmlFor="u-division" required><select id="u-division" value={v.division} onChange={e=>set('division',e.target.value as AdminUserDivision)} className={fieldClass()}>{['RENTAL','OUTRIGHT','WORKSHOP','AC','PRODUCTION','ELECTRONIC'].map(x=><option key={x}>{x}</option>)}</select></FormField><FormField label="Area" htmlFor="u-area" required><select id="u-area" value={v.area} onChange={e=>set('area',e.target.value as AdminUserArea)} className={fieldClass()}><option>COLOMBO</option><option>OUTSTATION</option><option>SUBURB</option></select></FormField>
  {kind==='coordinator'&&<FormField label="Coordinator role" htmlFor="u-role" required className="sm:col-span-2"><select id="u-role" value={v.coordinatorRole} onChange={e=>set('coordinatorRole',e.target.value as CoordinatorRole)} className={fieldClass()}><option>AREA_MANAGER</option><option>MANAGER</option><option>DATA_ENTRY_OPERATOR</option></select></FormField>}
  {!editing&&<fieldset className="sm:col-span-2"><legend className="mb-2 text-sm font-medium">Companies <span className="text-accent-500">*</span></legend><div className="flex gap-2">{(['GESTETNER','FINTECH'] as AdminUserCompany[]).map(c=>{const active=v.companies.includes(c);return<button key={c} type="button" onClick={()=>set('companies',active?v.companies.filter(x=>x!==c):[...v.companies,c])} className={`inline-flex h-9 items-center gap-1.5 rounded-full border px-3.5 text-sm ${active?'border-brand-500 bg-brand-50 text-brand-700':'border-line text-ink-muted'}`}>{active&&<CheckIcon className="h-3.5 w-3.5"/>}{c}</button>;})}</div>{errors.companies&&<p className="mt-1.5 text-xs text-danger-700">{errors.companies}</p>}</fieldset>}
  {editing&&<div className="rounded-lg bg-canvas px-4 py-3 text-sm text-ink-muted sm:col-span-2">Company assignments cannot be changed by the update endpoint. Current: {v.companies.join(', ')}</div>}
  <label className="flex items-center justify-between rounded-lg border border-line px-4 py-3 sm:col-span-2"><span className="text-sm font-medium">Active user</span><input type="checkbox" checked={v.isActive} onChange={e=>set('isActive',e.target.checked)}/></label></div></Modal>;
}
