'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { ChevronRightIcon, PlusIcon, SearchIcon, SearchXIcon, XIcon } from 'lucide-react';
import { toast } from 'sonner';
import { cancelBreakdown, changeBreakdownTechnician, completeBreakdown, createBreakdown, getBreakdown, getBreakdowns, startBreakdown, type BreakdownReportedByType, type BreakdownResponse } from '../apis/breakdowns';
import { getMachines, type MachineResponse } from '../apis/machines';
import { getTechnicians, type TechnicianResponse } from '../apis/technicians';
import { getSolutionTypes, type SolutionTypeResponse } from '../apis/solutionTypes';
import { Button } from '../components/ui/Button';
import { Drawer } from '../components/ui/Drawer';
import { FormField } from '../components/ui/FormField';
import { Modal } from '../components/ui/Modal';
import { StatusBadge, type BadgeTone } from '../components/ui/StatusBadge';
import { fieldClass } from '../utils/styles';

const tone = (status: string): BadgeTone => status === 'COMPLETED' ? 'success' : status === 'CANCELLED' ? 'danger' : status === 'PROCESSING' ? 'warning' : 'info';
const label = (value: string) => value.replaceAll('_', ' ').toLowerCase().replace(/\b\w/g, (x) => x.toUpperCase());
const dateTime = (value: string | null) => value ? new Date(value).toLocaleString() : '—';
const terminal = (status: string) => ['COMPLETED', 'CANCELLED'].includes(status);

export function Breakdowns() {
  const [items, setItems] = useState<BreakdownResponse[]>([]); const [machines, setMachines] = useState<MachineResponse[]>([]); const [techs, setTechs] = useState<TechnicianResponse[]>([]); const [solutionTypes, setSolutionTypes] = useState<SolutionTypeResponse[]>([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [query, setQuery] = useState(''); const [status, setStatus] = useState('ALL');
  const [selected, setSelected] = useState<BreakdownResponse | null>(null); const [detailLoading, setDetailLoading] = useState(false);
  const [createOpen, setCreateOpen] = useState(false); const [reassignOpen, setReassignOpen] = useState(false); const [cancelOpen, setCancelOpen] = useState(false); const [saving, setSaving] = useState(false); const [formError, setFormError] = useState('');
  const [startOpen, setStartOpen] = useState(false); const [completeOpen, setCompleteOpen] = useState(false); const [startNote, setStartNote] = useState(''); const [meterCounterTypeId, setMeterCounterTypeId] = useState(''); const [meterReading, setMeterReading] = useState(''); const [meterReadingNote, setMeterReadingNote] = useState(''); const [actualSolutionTypeId, setActualSolutionTypeId] = useState(''); const [solutionNote, setSolutionNote] = useState('');
  const [machineId, setMachineId] = useState(''); const [reportedType, setReportedType] = useState<BreakdownReportedByType>('DATA_ENTRY_OPERATOR'); const [portalId, setPortalId] = useState(''); const [reportedNote, setReportedNote] = useState(''); const [solutionTypeId, setSolutionTypeId] = useState(''); const [expectedAt, setExpectedAt] = useState(''); const [email, setEmail] = useState(''); const [technicianId, setTechnicianId] = useState(''); const [reason, setReason] = useState(''); const [cancelReason, setCancelReason] = useState('');

  const load = useCallback(async () => { setLoading(true); setError(null); try { const [a,b,c,d] = await Promise.all([getBreakdowns(), getMachines(), getTechnicians(), getSolutionTypes()]); setItems(a); setMachines(b); setTechs(c); setSolutionTypes(d); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load breakdowns.'); } finally { setLoading(false); } }, []);
  useEffect(() => { let cancelled=false; Promise.all([getBreakdowns(),getMachines(),getTechnicians(),getSolutionTypes()]).then(([a,b,c,d])=>{if(!cancelled){setItems(a);setMachines(b);setTechs(c);setSolutionTypes(d);}}).catch((e:unknown)=>{if(!cancelled)setError(e instanceof Error?e.message:'Unable to load breakdowns.');}).finally(()=>{if(!cancelled)setLoading(false);}); return()=>{cancelled=true;}; }, []);
  const currentUserId=()=>{const raw=localStorage.getItem('currentUser')??sessionStorage.getItem('currentUser');try{const id=raw?Number((JSON.parse(raw)as{userId?:number}).userId):0;if(!id)throw new Error();return id;}catch{throw new Error('Your user session is missing. Please sign in again.');}};
  const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return items.filter(x=>(status==='ALL'||x.status===status)&&(!q||[x.breakdownNumber,x.machineReferenceNumber,x.siteName,x.contactEmail].some(v=>v.toLowerCase().includes(q))));},[items,query,status]);
  const selectedMachine=machines.find(x=>String(x.machineId)===machineId); const activeTechs=techs.filter(x=>x.user.isActive); const activeSolutionTypes=solutionTypes.filter(x=>x.isActive);
  const openDetail=async(x:BreakdownResponse)=>{setSelected(null);setDetailLoading(true);try{setSelected(await getBreakdown(x.breakdownId));}catch(e){toast.error(e instanceof Error?e.message:'Unable to load breakdown.');}finally{setDetailLoading(false);}};
  const openCreate=()=>{setMachineId('');setReportedType('DATA_ENTRY_OPERATOR');setPortalId('');setReportedNote('');setSolutionTypeId('');setExpectedAt('');setEmail('');setTechnicianId('');setReason('Assigned based on customer area');setFormError('');setCreateOpen(true);};
  const submitCreate=async()=>{const machine=selectedMachine;if(!machine){setFormError('Select a machine.');return;}if(!technicianId){setFormError('Select a technician.');return;}if(!/^\S+@\S+\.\S+$/.test(email)){setFormError('Enter a valid contact email.');return;}if(reportedType==='PORTAL_CONTACT'&&!portalId){setFormError('Portal account ID is required for a portal contact.');return;}setSaving(true);setFormError('');try{const userId=currentUserId();const result=await createBreakdown({breakdown:{machineId:machine.machineId,customerSiteId:machine.customerSiteId,reportedByType:reportedType,reportedByPortalAccountId:portalId?Number(portalId):null,reportedByUserId:reportedType==='PORTAL_CONTACT'?null:userId,reportedNote:reportedNote.trim()||null,informedSolutionTypeId:solutionTypeId?Number(solutionTypeId):null,status:'PROCESSING',approvedBy:null,startNote:null,actualSolutionTypeId:null,solutionNote:null,cancelledBy:null,cancelReason:null,expectedCompletionAt:expectedAt||null,contactEmail:email.trim()},technicianAssignment:{technicianId:Number(technicianId),assignedBy:userId,assignmentStatus:'CURRENT',reason:reason.trim()||null}});setItems(p=>[result.breakdown,...p]);setSelected(result.breakdown);setCreateOpen(false);toast.success(`${result.breakdown.breakdownNumber} created and assigned`);}catch(e){const m=e instanceof Error?e.message:'Unable to create breakdown.';setFormError(m);toast.error(m);}finally{setSaving(false);}};
  const submitReassign=async()=>{if(!selected||!technicianId)return;setSaving(true);setFormError('');try{await changeBreakdownTechnician(selected.breakdownId,{technicianId:Number(technicianId),assignedBy:currentUserId(),reason:reason.trim()||null});const updated={...selected,status:'ASSIGNED' as const};setSelected(updated);setItems(p=>p.map(x=>x.breakdownId===updated.breakdownId?updated:x));setReassignOpen(false);toast.success('Technician changed successfully');}catch(e){const m=e instanceof Error?e.message:'Unable to change technician.';setFormError(m);toast.error(m);}finally{setSaving(false);}};
  const submitCancel=async()=>{if(!selected||!cancelReason.trim()){setFormError('Cancellation reason is required.');return;}setSaving(true);setFormError('');try{const updated=await cancelBreakdown(selected.breakdownId,{cancelledBy:currentUserId(),cancelReason:cancelReason.trim()});setSelected(updated);setItems(p=>p.map(x=>x.breakdownId===updated.breakdownId?updated:x));setCancelOpen(false);toast.success(`${updated.breakdownNumber} cancelled`);}catch(e){const m=e instanceof Error?e.message:'Unable to cancel breakdown.';setFormError(m);toast.error(m);}finally{setSaving(false);}};
  const openStart=(item:BreakdownResponse)=>{setSelected(item);setStartNote('');setMeterCounterTypeId('');setMeterReading('');setMeterReadingNote('');setFormError('');setStartOpen(true);};
  const submitStart=async()=>{if(!selected)return;if(!Number(meterCounterTypeId)){setFormError('Meter counter type ID is required.');return;}if(meterReading===''||!Number.isFinite(Number(meterReading))||Number(meterReading)<0){setFormError('Enter a valid meter reading.');return;}setSaving(true);setFormError('');try{const result=await startBreakdown(selected.breakdownId,{startNote:startNote.trim()||null,meterCounterTypeId:Number(meterCounterTypeId),meterReading:Number(meterReading),capturedByUserId:currentUserId(),meterReadingNote:meterReadingNote.trim()||null});setSelected(result.breakdown);setItems(p=>p.map(x=>x.breakdownId===result.breakdown.breakdownId?result.breakdown:x));setStartOpen(false);toast.success(`${result.breakdown.breakdownNumber} started`);}catch(e){const m=e instanceof Error?e.message:'Unable to start breakdown.';setFormError(m);toast.error(m);}finally{setSaving(false);}};
  const openComplete=(item:BreakdownResponse)=>{setSelected(item);setActualSolutionTypeId('');setSolutionNote('');setFormError('');setCompleteOpen(true);};
  const submitComplete=async()=>{if(!selected)return;if(!Number(actualSolutionTypeId)){setFormError('Actual solution type ID is required.');return;}setSaving(true);setFormError('');try{const updated=await completeBreakdown(selected.breakdownId,{actualSolutionTypeId:Number(actualSolutionTypeId),solutionNote:solutionNote.trim()||null});setSelected(updated);setItems(p=>p.map(x=>x.breakdownId===updated.breakdownId?updated:x));setCompleteOpen(false);toast.success(`${updated.breakdownNumber} completed`);}catch(e){const m=e instanceof Error?e.message:'Unable to complete breakdown.';setFormError(m);toast.error(m);}finally{setSaving(false);}};

  return <div className="mx-auto max-w-7xl"><div className="flex items-end justify-between gap-4"><div><h1 className="text-2xl font-semibold text-ink">Breakdowns</h1><p className="mt-1 text-sm text-ink-muted">{items.length} breakdown calls</p></div><Button icon={<PlusIcon className="h-4 w-4"/>} onClick={openCreate}>Create breakdown</Button></div>
    <div className="mt-6 overflow-hidden rounded-xl border border-line bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-line p-4 sm:flex-row"><div className="flex h-10 flex-1 items-center rounded-lg border border-line sm:max-w-xl"><SearchIcon className="ml-3 h-4 w-4 text-ink-subtle"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search breakdown, machine, site or email" className="h-full min-w-0 flex-1 bg-transparent px-2.5 text-sm outline-none"/>{query&&<button onClick={()=>setQuery('')} className="mr-2"><XIcon className="h-4 w-4"/></button>}</div><select value={status} onChange={e=>setStatus(e.target.value)} className="h-10 rounded-lg border border-line bg-white px-3 text-sm"><option value="ALL">All statuses</option>{['PROCESSING','ASSIGNED','STARTED','COMPLETED','CANCELLED'].map(x=><option key={x} value={x}>{label(x)}</option>)}</select></div>
    {loading?<p className="py-16 text-center text-sm text-ink-muted">Loading breakdowns…</p>:error?<div className="py-16 text-center"><p className="text-sm text-danger-700">{error}</p><Button variant="secondary" className="mt-4" onClick={()=>void load()}>Try again</Button></div>:filtered.length?<div className="overflow-x-auto"><table className="w-full min-w-[1060px] text-left text-sm"><thead className="border-b border-line bg-canvas/60 text-xs text-ink-muted"><tr><th className="px-5 py-3">Breakdown</th><th className="px-5 py-3">Machine</th><th className="px-5 py-3">Site</th><th className="px-5 py-3">Expected completion</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Actions</th><th/></tr></thead><tbody className="divide-y divide-line">{filtered.map(x=><tr key={x.breakdownId} onClick={()=>void openDetail(x)} className="group cursor-pointer hover:bg-brand-50/50"><td className="px-5 py-3.5"><p className="font-mono font-medium group-hover:text-brand-700">{x.breakdownNumber}</p><p className="text-xs text-ink-subtle">{label(x.reportedByType)}</p></td><td className="px-5 py-3.5 font-mono">{x.machineReferenceNumber}</td><td className="px-5 py-3.5">{x.siteName}</td><td className="px-5 py-3.5 text-ink-muted">{dateTime(x.expectedCompletionAt)}</td><td className="px-5 py-3.5"><StatusBadge tone={tone(x.status)} label={label(x.status)}/></td><td className="px-5 py-3.5"><div className="flex justify-end gap-2"><Button className="h-8 px-3" disabled={!['ASSIGNED','TRAVELLING'].includes(x.status)} onClick={e=>{e.stopPropagation();openStart(x);}}>Start</Button><Button variant="secondary" className="h-8 px-3" disabled={x.status!=='STARTED'} onClick={e=>{e.stopPropagation();openComplete(x);}}>Complete</Button></div></td><td><ChevronRightIcon className="h-4 w-4"/></td></tr>)}</tbody></table></div>:<div className="py-16 text-center"><SearchXIcon className="mx-auto h-8 w-8 text-ink-subtle"/><p className="mt-3 text-sm">No breakdowns found</p></div>}</div>
    <Drawer open={detailLoading||!!selected} onClose={()=>setSelected(null)} labelledBy="breakdown-title" widthClass="max-w-2xl"><div className="px-6 py-7 sm:px-8">{detailLoading?<p className="py-16 text-center">Loading…</p>:selected&&<><div className="pr-10"><div className="flex gap-2"><span className="font-mono text-xs text-ink-muted">ID #{selected.breakdownId}</span><StatusBadge tone={tone(selected.status)} label={label(selected.status)}/></div><h2 id="breakdown-title" className="mt-2 font-mono text-xl font-semibold">{selected.breakdownNumber}</h2><p className="mt-1 text-sm text-ink-muted">{selected.machineReferenceNumber} · {selected.siteName}</p></div><div className="mt-5 flex flex-wrap gap-2"><Button disabled={!['ASSIGNED','TRAVELLING'].includes(selected.status)} onClick={()=>openStart(selected)}>Start</Button><Button disabled={selected.status!=='STARTED'} onClick={()=>openComplete(selected)}>Complete</Button>{!terminal(selected.status)&&<><Button variant="secondary" onClick={()=>{setTechnicianId('');setReason('');setFormError('');setReassignOpen(true);}}>Change technician</Button><Button variant="secondary" onClick={()=>{setCancelReason('');setFormError('');setCancelOpen(true);}}>Cancel breakdown</Button></>}</div><dl className="mt-7 grid gap-5 border-t border-line pt-6 sm:grid-cols-2">{[['Contact email',selected.contactEmail],['Reported by',label(selected.reportedByType)],['Reported note',selected.reportedNote||'—'],['Created at',dateTime(selected.createdAt)],['Expected completion',dateTime(selected.expectedCompletionAt)],['Started at',dateTime(selected.startedAt)],['Completed at',dateTime(selected.completedAt)],['Solution note',selected.solutionNote||'—'],['Cancelled at',dateTime(selected.cancelledAt)],['Cancel reason',selected.cancelReason||'—']].map(([a,b])=><div key={String(a)}><dt className="text-xs text-ink-subtle">{a}</dt><dd className="mt-1 text-sm text-ink">{b}</dd></div>)}</dl></>}</div></Drawer>
    <Modal open={createOpen} onClose={()=>!saving&&setCreateOpen(false)} title="Create breakdown" description="Log the call and assign a technician." widthClass="max-w-3xl" footer={<div className="flex justify-end gap-3"><Button variant="ghost" disabled={saving} onClick={()=>setCreateOpen(false)}>Cancel</Button><Button loading={saving} onClick={()=>void submitCreate()}>Create & assign</Button></div>}>
      <div className="grid gap-4 sm:grid-cols-2">
        {formError&&<p className="rounded-lg bg-danger-50 p-3 text-sm text-danger-700 sm:col-span-2">{formError}</p>}
        <FormField label="Machine" htmlFor="bd-machine" required><select id="bd-machine" value={machineId} onChange={e=>{setMachineId(e.target.value);const m=machines.find(x=>String(x.machineId)===e.target.value);if(m)setEmail(m.email);}} className={fieldClass()}><option value="">Select machine</option>{machines.map(x=><option key={x.machineId} value={x.machineId}>{x.machineReferenceNumber} · {x.siteName}</option>)}</select></FormField>
        <FormField label="Customer site" htmlFor="bd-site"><input id="bd-site" disabled value={selectedMachine?`${selectedMachine.siteName} (#${selectedMachine.customerSiteId})`:''} className={fieldClass()}/></FormField>
        <FormField label="Reported by type" htmlFor="bd-reported" required><select id="bd-reported" value={reportedType} onChange={e=>setReportedType(e.target.value as BreakdownReportedByType)} className={fieldClass()}>{['DATA_ENTRY_OPERATOR','PORTAL_CONTACT','TECHNICIAN','DEALER','SALESMAN'].map(x=><option key={x} value={x}>{label(x)}</option>)}</select></FormField>
        {reportedType==='PORTAL_CONTACT'&&<FormField label="Portal account ID" htmlFor="bd-portal" required><input id="bd-portal" type="number" min="1" value={portalId} onChange={e=>setPortalId(e.target.value)} className={fieldClass()}/></FormField>}
        <FormField label="Contact email" htmlFor="bd-email" required><input id="bd-email" type="email" value={email} onChange={e=>setEmail(e.target.value)} className={fieldClass()}/></FormField>
        <FormField label="Expected completion" htmlFor="bd-expected"><input id="bd-expected" type="datetime-local" value={expectedAt} onChange={e=>setExpectedAt(e.target.value)} className={fieldClass()}/></FormField>
        <FormField label="Technician" htmlFor="bd-tech" required><select id="bd-tech" value={technicianId} onChange={e=>setTechnicianId(e.target.value)} className={fieldClass()}><option value="">Select technician</option>{activeTechs.map(x=><option key={x.technicianId} value={x.technicianId}>{x.user.userName} · {x.techCode}</option>)}</select></FormField>
        <FormField label="Informed solution" htmlFor="bd-solution"><select id="bd-solution" value={solutionTypeId} onChange={e=>setSolutionTypeId(e.target.value)} className={fieldClass()}><option value="">None</option>{activeSolutionTypes.map(x=><option key={x.solutionTypeId} value={x.solutionTypeId}>{x.solutionCode.replaceAll('_',' ')} · {x.solutionDescription}</option>)}</select></FormField>
        <FormField label="Reported note" htmlFor="bd-note" className="sm:col-span-2"><textarea id="bd-note" value={reportedNote} onChange={e=>setReportedNote(e.target.value)} rows={3} className={`${fieldClass()} py-2`}/></FormField>
        <FormField label="Assignment reason" htmlFor="bd-reason" className="sm:col-span-2"><textarea id="bd-reason" value={reason} onChange={e=>setReason(e.target.value)} rows={2} className={`${fieldClass()} py-2`}/></FormField>
      </div>
    </Modal>
    <Modal open={reassignOpen} onClose={()=>!saving&&setReassignOpen(false)} title="Change assigned technician" description={selected?.breakdownNumber} widthClass="max-w-lg" footer={<div className="flex justify-end gap-3"><Button variant="ghost" disabled={saving} onClick={()=>setReassignOpen(false)}>Cancel</Button><Button loading={saving} disabled={!technicianId} onClick={()=>void submitReassign()}>Assign technician</Button></div>}><div className="space-y-4">{formError&&<p className="rounded-lg bg-danger-50 p-3 text-sm text-danger-700">{formError}</p>}<FormField label="New technician" htmlFor="reassign-tech" required><select id="reassign-tech" value={technicianId} onChange={e=>setTechnicianId(e.target.value)} className={fieldClass()}><option value="">Select technician</option>{activeTechs.map(x=><option key={x.technicianId} value={x.technicianId}>{x.user.userName} · {x.techCode}</option>)}</select></FormField><FormField label="Reason" htmlFor="reassign-reason"><textarea id="reassign-reason" value={reason} onChange={e=>setReason(e.target.value)} rows={3} className={`${fieldClass()} py-2`}/></FormField></div></Modal>
    <Modal open={cancelOpen} onClose={()=>!saving&&setCancelOpen(false)} title="Cancel breakdown" description="This also closes the active technician assignment." widthClass="max-w-lg" footer={<div className="flex justify-end gap-3"><Button variant="ghost" disabled={saving} onClick={()=>setCancelOpen(false)}>Keep breakdown</Button><Button loading={saving} onClick={()=>void submitCancel()}>Cancel breakdown</Button></div>}><div className="space-y-4">{formError&&<p className="rounded-lg bg-danger-50 p-3 text-sm text-danger-700">{formError}</p>}<FormField label="Cancellation reason" htmlFor="cancel-reason" required><textarea id="cancel-reason" value={cancelReason} onChange={e=>setCancelReason(e.target.value)} rows={4} className={`${fieldClass()} py-2`}/></FormField></div></Modal>
    <Modal open={startOpen} onClose={()=>!saving&&setStartOpen(false)} title="Start breakdown job" description={selected?.breakdownNumber} widthClass="max-w-xl" footer={<div className="flex justify-end gap-3"><Button variant="ghost" disabled={saving} onClick={()=>setStartOpen(false)}>Cancel</Button><Button loading={saving} onClick={()=>void submitStart()}>Start breakdown</Button></div>}><div className="grid gap-4 sm:grid-cols-2">{formError&&<p className="rounded-lg bg-danger-50 p-3 text-sm text-danger-700 sm:col-span-2">{formError}</p>}<FormField label="Meter counter type ID" htmlFor="start-counter" required><input id="start-counter" type="number" min="1" value={meterCounterTypeId} onChange={e=>setMeterCounterTypeId(e.target.value)} className={fieldClass()}/></FormField><FormField label="Meter reading" htmlFor="start-reading" required><input id="start-reading" type="number" min="0" value={meterReading} onChange={e=>setMeterReading(e.target.value)} className={fieldClass()}/></FormField><FormField label="Start note" htmlFor="start-note" className="sm:col-span-2"><textarea id="start-note" value={startNote} onChange={e=>setStartNote(e.target.value)} rows={3} placeholder="Machine inspection started" className={`${fieldClass()} py-2`}/></FormField><FormField label="Meter reading note" htmlFor="meter-note" className="sm:col-span-2"><textarea id="meter-note" value={meterReadingNote} onChange={e=>setMeterReadingNote(e.target.value)} rows={3} placeholder="Meter reading captured before repair" className={`${fieldClass()} py-2`}/></FormField></div></Modal>
    <Modal open={completeOpen} onClose={()=>!saving&&setCompleteOpen(false)} title="Complete breakdown job" description={selected?.breakdownNumber} widthClass="max-w-lg" footer={<div className="flex justify-end gap-3"><Button variant="ghost" disabled={saving} onClick={()=>setCompleteOpen(false)}>Cancel</Button><Button loading={saving} onClick={()=>void submitComplete()}>Complete breakdown</Button></div>}><div className="space-y-4">{formError&&<p className="rounded-lg bg-danger-50 p-3 text-sm text-danger-700">{formError}</p>}<FormField label="Actual solution" htmlFor="complete-solution" required><select id="complete-solution" value={actualSolutionTypeId} onChange={e=>setActualSolutionTypeId(e.target.value)} className={fieldClass()}><option value="">Select solution</option>{activeSolutionTypes.map(x=><option key={x.solutionTypeId} value={x.solutionTypeId}>{x.solutionCode.replaceAll('_',' ')} · {x.solutionDescription}</option>)}</select></FormField><FormField label="Solution note" htmlFor="complete-note"><textarea id="complete-note" value={solutionNote} onChange={e=>setSolutionNote(e.target.value)} rows={4} placeholder="Describe the repair and testing performed" className={`${fieldClass()} py-2`}/></FormField></div></Modal>
  </div>;
}
