'use client';
import { useCallback, useEffect, useMemo, useState } from 'react'; import { PlusIcon, SearchIcon, SearchXIcon, XIcon } from 'lucide-react'; import { toast } from 'sonner';
import { createManagedUser, deleteManagedUser, getManagedUser, getManagedUsers, managedUserId, updateManagedUser, type ManagedUserCreateRequest, type ManagedUserKind, type ManagedUserResponse, type ManagedUserUpdateRequest } from '../apis/adminUsers'; import { ApiError } from '../apis/http';
import { Button } from '../components/ui/Button'; import { SegmentedControl } from '../components/ui/SegmentedControl'; import { ManagedUsersTable } from '../components/adminUsers/ManagedUsersTable'; import { ManagedUserDrawer } from '../components/adminUsers/ManagedUserDrawer'; import { ManagedUserDialog } from '../components/adminUsers/ManagedUserDialog';

export function ManagedUsers({kind}:{kind:ManagedUserKind}){
 const[users,setUsers]=useState<ManagedUserResponse[]>([]);const[query,setQuery]=useState('');const[status,setStatus]=useState<'all'|'active'|'inactive'>('all');const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[dialogOpen,setDialogOpen]=useState(false);const[editing,setEditing]=useState<ManagedUserResponse|null>(null);const[selected,setSelected]=useState<ManagedUserResponse|null>(null);const[detailLoading,setDetailLoading]=useState(false);const[detailError,setDetailError]=useState<string|null>(null);const[deleting,setDeleting]=useState(false);
 const label=kind==='coordinator'?'Coordinator':'Finance';const plural=kind==='coordinator'?'coordinators':'finance users';
 const load=useCallback(async()=>{setLoading(true);setError(null);try{setUsers(await getManagedUsers(kind));}catch(e){setError(e instanceof Error?e.message:`Unable to load ${plural}.`);}finally{setLoading(false);}},[kind,plural]);
 useEffect(()=>{let cancelled=false;getManagedUsers(kind).then(x=>{if(!cancelled)setUsers(x);}).catch((e:unknown)=>{if(!cancelled)setError(e instanceof Error?e.message:`Unable to load ${plural}.`);}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true;};},[kind,plural]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return users.filter(x=>{if(status==='active'&&!x.user.isActive)return false;if(status==='inactive'&&x.user.isActive)return false;return !q||x.user.userName.toLowerCase().includes(q)||x.user.email.toLowerCase().includes(q)||x.user.mobileNumber.includes(q);});},[users,query,status]);const active=users.filter(x=>x.user.isActive).length;
 const adminId=()=>{const raw=localStorage.getItem('currentUser')??sessionStorage.getItem('currentUser');const id=raw?Number((JSON.parse(raw) as{userId?:number}).userId):0;if(!id)throw new Error('Your user session is missing. Please sign in again.');return id;};
 const openDetail=async(x:ManagedUserResponse)=>{setSelected(null);setDetailError(null);setDetailLoading(true);try{setSelected(await getManagedUser(kind,managedUserId(kind,x)));}catch(e){setDetailError(e instanceof Error?e.message:'Unable to load details.');}finally{setDetailLoading(false);}};
 const save=async(request:Omit<ManagedUserCreateRequest,'createdBy'>|Omit<ManagedUserUpdateRequest,'updatedBy'>)=>{try{const result=editing?await updateManagedUser(kind,managedUserId(kind,editing),{...request,updatedBy:adminId()} as ManagedUserUpdateRequest):await createManagedUser(kind,{...request,createdBy:adminId()} as ManagedUserCreateRequest);setUsers(p=>editing?p.map(x=>managedUserId(kind,x)===managedUserId(kind,result)?result:x):[result,...p]);setSelected(result);setDialogOpen(false);setEditing(null);toast.success(`${label} ${editing?'updated':'created'}`);}catch(e){toast.error(e instanceof ApiError||e instanceof Error?e.message:`Unable to save ${label.toLowerCase()}.`);throw e;}};
 const remove=async(x:ManagedUserResponse)=>{if(!window.confirm(`Delete ${x.user.userName}? This cannot be undone.`))return;setDeleting(true);try{await deleteManagedUser(kind,managedUserId(kind,x));setUsers(p=>p.filter(u=>managedUserId(kind,u)!==managedUserId(kind,x)));setSelected(null);toast.success(`${label} deleted`);}catch(e){toast.error(e instanceof Error?e.message:'Delete failed.');}finally{setDeleting(false);}};
 return <div className="mx-auto max-w-7xl"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-semibold text-ink">{label} Users</h1><p className="mt-1 text-sm text-ink-muted">{users.length} {plural} · {active} active</p></div><Button icon={<PlusIcon className="h-4 w-4"/>} onClick={()=>{setEditing(null);setDialogOpen(true);}}>Create {label.toLowerCase()}</Button></div>
 <div className="mt-6 overflow-hidden rounded-xl border border-line bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-line p-4 lg:flex-row"><div className="flex h-10 flex-1 items-center rounded-lg border border-line focus-within:border-brand-500 focus-within:ring-2 focus-within:ring-brand-500/20 lg:max-w-md"><SearchIcon className="ml-3 h-4 w-4 text-ink-subtle"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, email or mobile" className="h-full min-w-0 flex-1 bg-transparent px-2.5 text-sm outline-none"/>{query&&<button onClick={()=>setQuery('')} className="mr-2" aria-label="Clear search"><XIcon className="h-4 w-4"/></button>}</div><div className="lg:ml-auto"><SegmentedControl ariaLabel="Filter status" value={status} onChange={setStatus} options={[{value:'all',label:'All',count:users.length},{value:'active',label:'Active',count:active},{value:'inactive',label:'Inactive',count:users.length-active}]}/></div></div>
 {loading?<p className="px-6 py-16 text-center text-sm text-ink-muted">Loading {plural}…</p>:error?<div className="px-6 py-16 text-center"><p className="text-sm text-danger-700">{error}</p><Button variant="secondary" className="mt-5" onClick={()=>void load()}>Try again</Button></div>:filtered.length?<ManagedUsersTable kind={kind} users={filtered} onSelect={x=>void openDetail(x)}/>:<div className="px-6 py-16 text-center"><SearchXIcon className="mx-auto h-8 w-8 text-ink-subtle"/><p className="mt-3 text-sm font-medium">No {plural} found</p></div>}<div className="border-t border-line px-5 py-3 text-xs text-ink-muted">Showing {filtered.length} of {users.length}</div></div>
 <ManagedUserDrawer kind={kind} item={selected} loading={detailLoading} error={detailError} deleting={deleting} onClose={()=>{setSelected(null);setDetailError(null);}} onEdit={x=>{setEditing(x);setDialogOpen(true);}} onDelete={x=>void remove(x)}/><ManagedUserDialog kind={kind} open={dialogOpen} item={editing} onClose={()=>{setDialogOpen(false);setEditing(null);}} onSave={save}/></div>;
}
