'use client';
import{useEffect,useState}from'react';import{toast}from'sonner';import{Modal}from'../ui/Modal';import{Button}from'../ui/Button';import{FormField}from'../ui/FormField';import{fieldClass}from'../../utils/styles';import{CatalogDialog,type CatalogValues}from'../catalogs/CatalogDialog';
import{createMachineType,createManufacturer,getMachineTypes,getManufacturers,type MachineTypeResponse,type ManufacturerResponse}from'../../apis/catalogs';import type{MachineCompany,MachineModelRequest,MachineModelResponse}from'../../apis/machines';
type Values={company:MachineCompany;manufacturerId:string;machineTypeId:string;modelNumber:string;modelName:string;description:string;isActive:boolean};const empty=():Values=>({company:'GESTETNER',manufacturerId:'',machineTypeId:'',modelNumber:'',modelName:'',description:'',isActive:true});
export function MachineModelDialog({open,model,onClose,onSave}:{open:boolean;model:MachineModelResponse|null;onClose:()=>void;onSave:(request:Omit<MachineModelRequest,'createdBy'>)=>Promise<void>}){const[v,setV]=useState<Values>(empty);const[errors,setErrors]=useState<Record<string,string>>({});const[saving,setSaving]=useState(false);const[manufacturers,setManufacturers]=useState<ManufacturerResponse[]>([]);const[types,setTypes]=useState<MachineTypeResponse[]>([]);const[catalog,setCatalog]=useState<'manufacturer'|'machineType'|null>(null);
 useEffect(()=>{if(!open)return;setV(model?{company:model.company,manufacturerId:String(model.manufacturerId),machineTypeId:String(model.machineTypeId),modelNumber:model.modelNumber,modelName:model.modelName,description:model.description??'',isActive:model.isActive}:empty());Promise.all([getManufacturers(),getMachineTypes()]).then(([a,b])=>{setManufacturers(a);setTypes(b);}).catch((e:unknown)=>toast.error(e instanceof Error?e.message:'Unable to load catalogue options.'));},[open,model]);
 const set=<K extends keyof Values>(k:K,x:Values[K])=>{setV(p=>({...p,[k]:x}));setErrors(p=>({...p,[k]:''}));};const adminId=()=>{const raw=localStorage.getItem('currentUser')??sessionStorage.getItem('currentUser');const id=raw?Number((JSON.parse(raw)as{userId?:number}).userId):0;if(!id)throw new Error('Your user session is missing.');return id;};
 const addCatalog=async(x:CatalogValues)=>{try{if(catalog==='manufacturer'){const created=await createManufacturer({manufacturerName:x.name,isActive:x.isActive,createdBy:adminId()});setManufacturers(p=>[...p,created]);set('manufacturerId',String(created.manufacturerId));toast.success('Manufacturer created');}else{const created=await createMachineType({machineTypeName:x.name,machineTypeDescription:x.description||null,isActive:x.isActive});setTypes(p=>[...p,created]);set('machineTypeId',String(created.machineTypeId));toast.success('Machine type created');}setCatalog(null);}catch(e){toast.error(e instanceof Error?e.message:'Unable to create option.');throw e;}};
 const submit=async()=>{const e:Record<string,string>={};if(!v.manufacturerId)e.manufacturerId='Select a manufacturer';if(!v.machineTypeId)e.machineTypeId='Select a machine type';if(!v.modelNumber.trim())e.modelNumber='Model number is required';if(!v.modelName.trim())e.modelName='Model name is required';if(v.modelNumber.trim().length>60)e.modelNumber='Maximum 60 characters';if(v.modelName.trim().length>150)e.modelName='Maximum 150 characters';if(v.description.length>255)e.description='Maximum 255 characters';setErrors(e);if(Object.keys(e).length)return;setSaving(true);try{await onSave({company:v.company,manufacturerId:Number(v.manufacturerId),machineTypeId:Number(v.machineTypeId),modelNumber:v.modelNumber.trim().toUpperCase(),modelName:v.modelName.trim(),description:v.description.trim()||null,isActive:v.isActive});}catch{}finally{setSaving(false);}};
 const input=(k:'modelNumber'|'modelName'|'description',label:string,required=false)=><FormField label={label} htmlFor={`mm-${k}`} required={required} error={errors[k]} className={k==='description'?'sm:col-span-2':''}><input id={`mm-${k}`} value={v[k]} maxLength={k==='modelNumber'?60:k==='modelName'?150:255} onChange={e=>set(k,e.target.value)} className={fieldClass(!!errors[k])}/></FormField>;
 return <><Modal open={open} onClose={()=>!saving&&!catalog&&onClose()} title={`${model?'Edit':'Create'} machine model`} description="Add a model to the machine catalogue." widthClass="max-w-xl" footer={<div className="flex justify-end gap-3"><Button variant="ghost" disabled={saving} onClick={onClose}>Cancel</Button><Button loading={saving} onClick={()=>void submit()}>{model?'Save changes':'Create model'}</Button></div>}><div className="grid gap-4 sm:grid-cols-2"><FormField label="Company" htmlFor="mm-company" required><select id="mm-company" value={v.company} onChange={e=>set('company',e.target.value as MachineCompany)} className={fieldClass()}><option>GESTETNER</option><option>FINTECH</option></select></FormField>
  <FormField label="Manufacturer" htmlFor="mm-manufacturer" required error={errors.manufacturerId} action={<button type="button" onClick={()=>setCatalog('manufacturer')} className="text-xs font-medium text-brand-700">+ Create</button>}><select id="mm-manufacturer" value={v.manufacturerId} onChange={e=>set('manufacturerId',e.target.value)} className={fieldClass(!!errors.manufacturerId)}><option value="">Select manufacturer</option>{manufacturers.filter(x=>x.isActive||String(x.manufacturerId)===v.manufacturerId).map(x=><option key={x.manufacturerId} value={x.manufacturerId}>{x.manufacturerName}</option>)}</select></FormField>
  <FormField label="Machine type" htmlFor="mm-type" required error={errors.machineTypeId} action={<button type="button" onClick={()=>setCatalog('machineType')} className="text-xs font-medium text-brand-700">+ Create</button>}><select id="mm-type" value={v.machineTypeId} onChange={e=>set('machineTypeId',e.target.value)} className={fieldClass(!!errors.machineTypeId)}><option value="">Select machine type</option>{types.filter(x=>x.isActive||String(x.machineTypeId)===v.machineTypeId).map(x=><option key={x.machineTypeId} value={x.machineTypeId}>{x.machineTypeName}</option>)}</select></FormField>
  {input('modelNumber','Model number',true)}{input('modelName','Model name',true)}{input('description','Description')}<label className="flex items-center justify-between rounded-lg border border-line px-4 py-3 sm:col-span-2"><span className="text-sm font-medium">Active model</span><input type="checkbox" checked={v.isActive} onChange={e=>set('isActive',e.target.checked)}/></label></div></Modal><CatalogDialog kind={catalog??'manufacturer'} open={!!catalog} item={null} onClose={()=>setCatalog(null)} onSave={addCatalog}/></>;
}
