'use client';
import { useEffect, useState } from 'react'; import { Modal } from '../ui/Modal'; import { Button } from '../ui/Button'; import { FormField } from '../ui/FormField'; import { fieldClass } from '../../utils/styles';
import type { MachineCompany, MachineModelRequest, MachineModelResponse } from '../../apis/machines';
type Values={company:MachineCompany;manufacturerId:string;machineTypeId:string;modelNumber:string;modelName:string;description:string;isActive:boolean};
const empty=():Values=>({company:'GESTETNER',manufacturerId:'',machineTypeId:'',modelNumber:'',modelName:'',description:'',isActive:true});
export function MachineModelDialog({open,model,onClose,onSave}:{open:boolean;model:MachineModelResponse|null;onClose:()=>void;onSave:(request:Omit<MachineModelRequest,'createdBy'>)=>Promise<void>}){
 const[v,setV]=useState<Values>(empty);const[errors,setErrors]=useState<Record<string,string>>({});const[saving,setSaving]=useState(false);
 useEffect(()=>{if(open)setV(model?{company:model.company,manufacturerId:String(model.manufacturerId),machineTypeId:String(model.machineTypeId),modelNumber:model.modelNumber,modelName:model.modelName,description:model.description??'',isActive:model.isActive}:empty());},[open,model]);
 const set=<K extends keyof Values>(k:K,x:Values[K])=>{setV(p=>({...p,[k]:x}));setErrors(p=>({...p,[k]:''}));};
 const submit=async()=>{const e:Record<string,string>={};if(!v.manufacturerId||Number(v.manufacturerId)<=0)e.manufacturerId='Enter a positive manufacturer ID';if(!v.machineTypeId||Number(v.machineTypeId)<=0)e.machineTypeId='Enter a positive machine type ID';if(!v.modelNumber.trim())e.modelNumber='Model number is required';if(!v.modelName.trim())e.modelName='Model name is required';if(v.modelNumber.trim().length>60)e.modelNumber='Maximum 60 characters';if(v.modelName.trim().length>150)e.modelName='Maximum 150 characters';if(v.description.length>255)e.description='Maximum 255 characters';setErrors(e);if(Object.keys(e).length)return;setSaving(true);try{await onSave({company:v.company,manufacturerId:Number(v.manufacturerId),machineTypeId:Number(v.machineTypeId),modelNumber:v.modelNumber.trim().toUpperCase(),modelName:v.modelName.trim(),description:v.description.trim()||null,isActive:v.isActive});}catch{}finally{setSaving(false);}};
 const input=(k:'manufacturerId'|'machineTypeId'|'modelNumber'|'modelName'|'description',label:string,type='text',required=false)=><FormField label={label} htmlFor={`mm-${k}`} required={required} error={errors[k]} className={k==='description'?'sm:col-span-2':''}><input id={`mm-${k}`} type={type} value={v[k]} maxLength={k==='modelNumber'?60:k==='modelName'?150:k==='description'?255:undefined} onChange={e=>set(k,e.target.value)} className={fieldClass(!!errors[k])}/></FormField>;
 return <Modal open={open} onClose={()=>!saving&&onClose()} title={`${model?'Edit':'Create'} machine model`} description="Add a model to the machine catalogue." widthClass="max-w-xl" footer={<div className="flex justify-end gap-3"><Button variant="ghost" disabled={saving} onClick={onClose}>Cancel</Button><Button loading={saving} onClick={()=>void submit()}>{model?'Save changes':'Create model'}</Button></div>}><div className="grid gap-4 sm:grid-cols-2"><FormField label="Company" htmlFor="mm-company" required><select id="mm-company" value={v.company} onChange={e=>set('company',e.target.value as MachineCompany)} className={fieldClass()}><option>GESTETNER</option><option>FINTECH</option></select></FormField>{input('manufacturerId','Manufacturer ID','number',true)}{input('machineTypeId','Machine type ID','number',true)}{input('modelNumber','Model number','text',true)}{input('modelName','Model name','text',true)}{input('description','Description')}<label className="flex items-center justify-between rounded-lg border border-line px-4 py-3 sm:col-span-2"><span className="text-sm font-medium">Active model</span><input type="checkbox" checked={v.isActive} onChange={e=>set('isActive',e.target.checked)}/></label></div></Modal>;
}
